version: "3.7"

services:
    broker:
        image: hivemq/hivemq4:latest
        container_name: broker
        environment: 
            - HIVEMQ_CONTROL_CENTER_USER=test
            - HIVEMQ_CONTROL_CENTER_PASSWORD=test
        ports:
            - "1883:1883"
            - "8080:8080"
    mongodb:
        image: mongo
        container_name: mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=test
            - MONGO_INITDB_ROOT_PASSWORD=test
        ports:
            - "27017:27017"