version: "3.7"

services:
    broker:
        image: hivemq/hivemq4:latest
        container_name: broker
        environment: 
            - HIVEMQ_CONTROL_CENTER_USER=test
            - HIVEMQ_CONTROL_CENTER_PASSWORD=test
        ports:
            - "1883:1883"
    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - "27017:27017"