MONGODB_HOST: localhost
MONGODB_PORT: 27017
MONGODB_DB: iottcc

BROKER_MQTT_HOST: localhost
BROKER_MQTT_PORT: 1883
BROKER_MQTT_PASSWORD: test
BROKER_MQTT_USER: test
MQTT_TOPIC_DEVICES: devices
MQTT_TOPIC_MEASUREMENTS: devices/+/measurements