// Code generated by mockery v2.7.4. DO NOT EDIT.

package user

import (
	mock "github.com/stretchr/testify/mock"
	entity "github.com/thyagofr/tcc/api/domain/entity"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// Login provides a mock function with given fields: email, password
func (_m *MockService) Login(email string, password string) (*entity.User, error) {
	ret := _m.Called(email, password)

	var r0 *entity.User
	if rf, ok := ret.Get(0).(func(string, string) *entity.User); ok {
		r0 = rf(email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: user
func (_m *MockService) Register(user *entity.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
