// Code generated by mockery v2.7.4. DO NOT EDIT.

package service

import mock "github.com/stretchr/testify/mock"

// MockCrypt is an autogenerated mock type for the Crypt type
type MockCrypt struct {
	mock.Mock
}

// Check provides a mock function with given fields: hash, password
func (_m *MockCrypt) Check(hash string, password string) (bool, error) {
	ret := _m.Called(hash, password)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(hash, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(hash, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Hash provides a mock function with given fields: password
func (_m *MockCrypt) Hash(password string) (string, error) {
	ret := _m.Called(password)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
