MONGODB_HOST=localhost
MONGODB_PORT=1234
MONGODB_COLLECTION=asdasd
MONGODB_DB=asdasd
MONGODB_USER=asdasdasd
MONGODB_PASSWORD=asdhasjd

BROKER_MQTT_HOST=
BROKER_MQTT_PORT=
BROKER_MQTT_PASSWORD=
BROKER_MQTT_USER=
MQTT_CLIENTID=AUSDHASJD
MQTT_TOPIC